version: "3"
services:
  scraper:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "scraper"
    networks:
      - "cbe_network"
    security_opt:
      - "seccomp=playwright/seccomp_profile.json"

networks:
  cbe_network:
    name: "cbe_network"
    driver: "bridge"

volumes:
  db_data:
    name: "db_data"
