version: "3"
services:
  redis:
    build:
      context: "./redis"
      dockerfile: "Dockerfile"
    ports:
      - "6379:6379"
    networks:
      - "scraper"
    volumes:
      - "redis_data:/data"
  scraper:
    build:
      context: "."
      dockerfile: "Dockerfile"
    image: "scraper"
    networks:
      - "scraper"
    security_opt:
      - "seccomp=playwright/seccomp_profile.json"
    depends_on:
      - "redis"

networks:
  scraper:
    name: "scraper"
    driver: "bridge"

volumes:
  redis_data:
    name: "redis_data"
